name: 💎 Article request
description: Article suggestion you want to be published on community.abp.io
labels: [community-article-request]
body:
- type: textarea
  attributes:
    label: Describe the article you'd like
    description: |
      Please describe the article you'd like to be published on community.abp.io.
      If you have any reference article, please share it here.
  validations:
    required: true
