blank_issues_enabled: true
contact_links:
  - name: Issue with ABP Commercial
    url:  https://support.abp.io/QA/Questions
    about: Please open issues relating to ABP Commercial in support.abp.io.
